from setuptools import find_packages, setup

setup(
    name="ingest",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.9",
    install_requires=[
        "litellm~=1.57.5",
        "sqlalchemy~=2.0.36",
        "psycopg2-binary",
        "asyncpg",
        "qdrant-client",
        "anthropic~=0.42.0",
        "google-generativeai>=0.7.0",
        "openai~=1.59.0",
        "tiktoken",
        "cohere",
        "mistral-common",
        "voyageai",
        "pydantic~=2.10.0",
        "aiohttp",
        "backoff",
        "typing_extensions",
        "beautifulsoup4",
        "numpy",
        "pandas",
        "tqdm",
        "modal",
        "marker-pdf",
        "instructor",
        "aiofiles",
        "pypdfium2",
        "pymupdf",
        "pyyaml",
        "crawlee",
        "fake_useragent",
        "crawl4ai",
        "python-dotenv",
        "sentence-transformers~=3.3.1",
        "spacy",
        "nltk",
        "scikit-learn",
        "umap-learn",
        "matplotlib",
        "seaborn",
        "python-docx",
        "pillow",
        "transformers~=4.47.1",
        "boto3",
        "textract-trp",
        "rapidfuzz",
        "google-labs-html-chunker",
        "fastembed",
        "magic-pdf[full]",
        "unstructured",
        "unstructured-client",
        "aioboto3",
        "networkx",
        "pyvis",
        "alembic"
    ],
    extras_require={
        "dev": [
            "pytest",
            "pytest-asyncio",
            "black",
            "ruff",
            "isort",
            "mypy",
            "mkdocs",
            "mkdocs-material",
            "mkdocstrings[python]",
            "mkdocs-gen-files",
            "mkdocs-literate-nav",
            "mkdocs-section-index",
        ]
    },
    author="Pranav Iyer",
    description="A data ingestion and processing pipeline",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Operating System :: OS Independent",
    ],
)
