"""add row expected

Revision ID: 17b18d55a2e6
Revises: a29cd0ba8a75
Create Date: 2024-12-22 22:18:03.071284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '17b18d55a2e6'
down_revision: Union[str, None] = 'a29cd0ba8a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rows', sa.Column('expected', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('rows', 'expected')
