"""add completed_at column

Revision ID: b451a2db093a
Revises: 4c11ebc3b19d
Create Date: 2024-12-16 13:28:45.518762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b451a2db093a'
down_revision: Union[str, None] = '4c11ebc3b19d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_assignments', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_assignments', 'completed_at')
    # ### end Alembic commands ###
