stages:
  - name: ingest
    functions:
      - name: local
        input: null
        return: Ingestion
        params:
          directory_path: "/Users/pranaviyer/Desktop/AstralisData"

  - name: parse
    functions:
      - name: textract
        input: Ingestion
        return: Entry

  - name: chunk
    functions:
      - name: sliding_window_chunking
        input: Entry
        return: Entry
        params:
          chunk_size: 600
          overlap: 200
          provider: "openai"
          model: "gpt-4o"
  
  - name: embed
    functions:
      - name: embed
        input: Entry
        return: Embedding
        params:
          model: "text-embedding-3-large"
          provider: "openai"
          embed_model_params:
            dimensions: 512
  
  - name: eval
    functions:
      - name: eval_embeddings
        input: Embedding
        return: Evaluation
        params:
          provider: "openai"
          model: "gpt-4o"
          max_tokens: 1000

pipeline:
  version: "1.0"
  description: "test_pipeline_kia_new"
  collection_name: "test_collection_kia"
  pipeline_id: 64
  resume_from_step: 3
  fork_pipeline: true

storage:
  type: "s3"
  bucket_name: "astralis-data-4170a4f6"
