# Individual pipeline evaluation settings
pipeline_evaluation:
  enabled: true
  evaluation_type: "LLM"
  pipeline_id: 21  # Single pipeline to evaluate
  model_name: "gpt-4o"
  model_params:
    temperature: 0.0
    max_tokens: 1000

# Output settings
output:
  save_results: true
  output_dir: "evaluation_results"
  metrics:
    - "quality_scores"

storage:
  storage_type: "s3"
  bucket_name: "astralis-data-4170a4f6"
