# Individual pipeline evaluation settings
pipeline_evaluation:
  evaluation_mode: "individual"
  evaluation_type: "LLM"
  pipeline_id: 21  # Single pipeline to evaluate
  filter_params:
    consolidated_feature_type: ["combined_text"]
  model_name: "gpt-4o-mini"
  model_params:
    temperature: 0.0
    max_tokens: 1000

# Output settings
output:
  save_results: true
  output_dir: "evaluation_results"
  metrics:
    - "quality_scores"

storage:
  storage_type: "s3"
  bucket_name: "astralis-data-4170a4f6"
