stages:
  - name: ingest
    functions:
      - name: local
        input: null
        return: Ingestion
        params:
          directory_path:
            - "/Users/pranaviyer/Desktop/AstralisData/"
            - "/Users/pranaviyer/Desktop/Papers to Read"
          added_metadata:
            document_title: "docbench"
            content_type: "other"
            ingestion_method: "local_file"
            file_type: "pdf"

  - name: extract
    functions:
      - name: simple
        input: Ingestion
        return: Entry

pipeline:
  version: "1.0"
  description: "test_pipeline_pranav_ingest_local"
  # pipeline_id: 1
  # resume_from_step: 2
  # update_on_collision: true  # Add this flag
  # fork_pipeline: true
  # collection_name: "test_collection_pranav"

storage:
  storage_type: "s3"
  bucket_name: "astralis-data-4170a4f6"
