stages:
  - name: ingest
    functions:
      - name: local
        input: null
        return: Ingestion
        params:
          directory_path: "C:/Users/marka/fun/ingest/local_files/"
          added_metadata:
            document_title: "docbench"
            content_type: "other"
            ingestion_method: "local_file"
            file_type: "pdf"

  - name: extract
    functions:
      - name: marker
        input: Ingestion
        return: Entry

  - name: featurize
    functions:
      - name: featurize_model
        input: Entry
        return: Entry
        params:
          prompt_name: "summarize_entry"
          model_name: "gpt-4o-mini"
    
  - name: embed
    functions:
      - name: embed
        input: Entry
        return: Embedding
        params:
          model_name: "openai"
          dimensions: 512

  - name: upsert
    functions:
      - name: upsert_embeddings
        input: Embedding
        return: Upsert
        params:
          collection_name: "test_collection_mark"
          dense_model_name: "text-embedding-3-large"
          sparse_model_name: "bm25"
          dimensions: 512
    
  - name: upsert
    functions:
      - name: upsert_entries
        input: Entry
        return: Upsert
        params:
          collection_name: "test_collection_mark"
          version: "1.0"
          update_on_collision: true


pipeline:
  description: "test_pipeline_mark_featurize"
  pipeline_id: 22
  # resume_from_step: 2
  # fork_pipeline: true

storage:
  storage_type: "local"
  base_path: "C:/Users/marka/fun/ingest/local_files/"
