stages:
  - name: ingest
    functions:
      - name: local
        input: null
        return: Ingestion
        params:
          directory_path: "C:/Users/marka/fun/ingest/local_files"

  - name: extract
    functions:
      - name: datalab
        input: Ingestion
        return: Entry

pipeline:
  version: "1.0"
  description: "test_pipeline_mark"
  collection_name: "test_collection_mark"

storage:
  storage_type: "local"
  base_path: "C:/Users/marka/fun/ingest/local_files"
